

const OWM_API_KEY = 'REPLACE_WITH_YOUR_OWM_KEY';
const OWM_LOCATION = 'Lagos,NG';
const OWM_UNITS = 'metric';


window.OWM_API_KEY = OWM_API_KEY;
window.OWM_LOCATION = OWM_LOCATION;
window.OWM_UNITS = OWM_UNITS;
